export const fieldsName = {
  gruppa: "Группа товара",
  podgruppa: "Подгруппа товара",

  osnova: "Основа",
  cvet: "Цвет",
  risunok: "Рисунок",
  naznachenie: "Назначение",
  type: "Тип",
  dizayn: "Дизайн",
  dlinaM: "Длина(м)",
  shirinaM: "Ширина(м)",

  sposob_montazha: "Способ монтажа",
  dlinaMM: "Длина (мм)",
  dlinaSM: "Длина (см)",
  shirinaMM: "Ширина (мм)",
  shirinaSM: "Ширина (см)",
  tolshina: "Толщина",
  tolshinaMM: "Толщина (мм)",
  vysotaMM: "Высота (мм)",
  vysotaM: "Высота (м)",
  vysotaSM: "Высота (см)",
  kolichestvo_chastey: "Количество частей",
  material: "Материал",
  faska: "Фаска",
  ottenok: "Оттенок",
  tip_plitki: "Тип плитки",
  mehanizm: "Механизм",
  tip_pomescheniya: "Тип помещения",
  shirina: "Ширина",
  vysota: "Высота",
  glubina: "Глубина",
  dlina: "Длина",
  razmer_spalnogo_mesta: "Размер спального места",
  chislo_mest: "Число мест",
  forma: "Форма",
  vid: "Вид",
  razmer: "Размер",
  dvertsy: "Дверцы",
  ves: "Вес",
  komplektyushie: "Комплектующие",
  orientatsiya: "Ориентация",
  obyem: "Объем",
  poddon: "Поддон",
  tolshina_polotna: "Толщина полотна",
  pokrytie: "Покрытие",
  polotno: "Полотно",
  temperatura_nagreva: "Температура нагрева",
  kategoriya: "Категория",
  diametr: "Диаметр",
  kamera_sgoraniya: "Камера сгорания",
  proizvoditelnost: "Производительность",
  vysota_podyema: "Высота подъема",
  glubina_pogruzheniya: "Глубина погружения",
  moschnost: "Мощность",
  kolichestvo_sekciy: "Количество секций",
  tip_podvodki: "Тип подводки",
  razmer_soedineniya: "Размерсоединения",
  poverhnost: "Поверхность",
  cokol: "Цоколь",
  kolichestvo_lamp: "Количество ламп",
  materialOtdelki: "Материал отделки",
  // description: "Описание",
};

export default fieldsName;
